# Generated by Django 2.1.3 on 2018-11-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
