# Generated by Django 2.1.3 on 2018-11-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gregblog', '0002_auto_20181115_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gregblog.Category', verbose_name='文章类别'),
        ),
    ]
