# Generated by Django 2.1.3 on 2018-11-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gregblog', '0003_auto_20181120_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
