# Generated by Django 2.1.3 on 2018-11-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户扩展信息', 'verbose_name_plural': '用户扩展信息'},
        ),
    ]
